version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ecommerce_network
    volumes:
      - zookeeper_data:/bitnami/zookeeper/data
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    command: >
      bash -c "rm -f /var/lib/kafka/data/meta.properties && /etc/confluent/docker/run"
    networks:
      - ecommerce_network
    healthcheck:
      test: [ "CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-mongodb:
    image: mongo:7.0.4
    container_name: user-mongodb
    ports:
      - "27017:27017"
    volumes:
      - user-mongodb-data:/data/db
    networks:
      - ecommerce_network
    environment:
      - MONGO_INITDB_DATABASE=user_db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cart-mongodb:
    image: mongo:7.0.4
    container_name: cart-mongodb
    ports:
      - "27018:27017"
    volumes:
      - cart-mongodb-data:/data/db
    networks:
      - ecommerce_network
    environment:
      - MONGO_INITDB_DATABASE=cart_db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  product-mongodb:
    image: mongo:7.0.4
    container_name: product-mongodb
    ports:
      - "27019:27017"
    volumes:
      - product-mongodb-data:/data/db
    networks:
      - ecommerce_network
    environment:
      - MONGO_INITDB_DATABASE=product_db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-mongodb:
    image: mongo:7.0.4
    container_name: order-mongodb
    ports:
      - "27020:27017"
    volumes:
      - order-mongodb-data:/data/db
    networks:
      - ecommerce_network
    environment:
      - MONGO_INITDB_DATABASE=order_db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: redis_cnpm
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - ecommerce_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./services/user-service
    container_name: user-service
    ports:
      - "7001:7001"
    depends_on:
      kafka:
        condition: service_healthy
      user-mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ecommerce_network
    environment:
      - KAFKA_BROKERS=kafka:9092
      - MONGODB_URI=mongodb://user-mongodb:27017/user_db
      - REDIS_HOST=redis_cnpm
      - REDIS_PORT=6379

  cart-service:
    build:
      context: ./services/cart-service
    container_name: cart-service
    ports:
      - "7003:7003"
    depends_on:
      kafka:
        condition: service_healthy
      cart-mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ecommerce_network
    environment:
      - KAFKA_BROKERS=kafka:9092
      - MONGODB_URI=mongodb://cart-mongodb:27017/cart_db
      - REDIS_HOST=redis_cnpm
      - REDIS_PORT=6379

  product-service:
    build:
      context: ./services/product-service
    container_name: product-service
    ports:
      - "7002:7002"
    depends_on:
      kafka:
        condition: service_healthy
      product-mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ecommerce_network
    environment:
      - KAFKA_BROKERS=kafka:9092
      - MONGODB_URI=mongodb://product-mongodb:27017/product_db
      - REDIS_HOST=redis_cnpm
      - REDIS_PORT=6379

  order-service:
    build:
      context: ./services/order-service
    container_name: order-service
    ports:
      - "7004:7004"
    depends_on:
      kafka:
        condition: service_healthy
      order-mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ecommerce_network
    environment:
      - KAFKA_BROKERS=kafka:9092
      - MONGODB_URI=mongodb://order-mongodb:27017/order_db
      - REDIS_HOST=redis_cnpm
      - REDIS_PORT=6379

  nginx:
    container_name: nginx-gateway
    build:
      context: ./services/gateway
    ports:
      - "80:80"
    depends_on:
      - user-service
      - cart-service
      - product-service
      - order-service
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  user-mongodb-data:
  cart-mongodb-data:
  product-mongodb-data:
  order-mongodb-data:
  redis_data:
  kafka_data:
  zookeeper_data: